version: '3.9'
services:
  server:
    # container_name: server
    build: .
    # ports:
    #   - 3000:3000

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - server
    ports:
      - 3000:3000
